site_name: Shin's Japanese Guide
nav:
  - 'index.md'
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: purple
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list